supabase_url = "https://hgxqgvqrnyuoyxnnptwt.supabase.co"
supabase_anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhneHFndnFybnl1b3l4bm5wdHd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMjQ4ODMsImV4cCI6MjA2MjcwMDg4M30._iHpVyA7umyoRVh8X8T1rU77QuPH-97WQ1-qf0rb-j0"
